import type { BlogPost } from "@/lib/blog";
export const post: BlogPost = {
  slug: "colorado-chance-to-compete-act-employer-guide",
  title:
    "Colorado Chance to Compete Act: The Ban-the-Box Statute Every Employer Hiring in CO Has To Operationalize",
  metaTitle: "Colorado Chance to Compete Act Employer Guide 2026",
  metaDescription:
    "Colorado's Chance to Compete Act (C.R.S. §8-2-130) bars criminal-history questions on job postings and applications. Here is the 2026 compliance map and CDLE penalty exposure.",
  excerpt:
    "Colorado's Chance to Compete Act bars criminal-history questions on job postings and initial applications, with narrow statutory exemptions and a Colorado Department of Labor enforcement track. We map the 2026 compliance scaffold for multistate employers.",
  publishedAt: "2026-05-29",
  readingMinutes: 6,
  author: "Rapid Hire Compliance Team",
  tags: ["colorado", "ban-the-box", "fair-chance", "compliance", "criminal-records"],
  body: `**Colorado Chance to Compete Act compliance** is the state ban-the-box audit our Denver and Boulder clients most often misread, because the statute looks superficially similar to the federal [EEOC ban-the-box framework](/blog/eeoc-ban-the-box-compliance) but its operative duties run further upstream. The **Chance to Compete Act** — Colo. Rev. Stat. **§8-2-130**, enacted by House Bill 19-1025 and fully in force for all Colorado employers since September 1, 2021 — bars Colorado employers from including criminal-history inquiries on job advertisements and on initial employment applications, and from stating in any advertisement or application that a person with a criminal history may not apply. The Colorado Department of Labor and Employment (CDLE) is the enforcement authority, and its 2024 advisory bulletin sharpened the rules around online job postings, third-party staffing agencies, and the interaction with the federal [FCRA disclosure framework](/blog/fcra-604b-disclosure-authorization) that multistate employers regularly underestimate.

## What the Chance to Compete Act actually restricts
The statute creates two distinct upstream duties. **§8-2-130(2)(a)** prohibits an employer from advertising that a person with a criminal history may not apply for a position. **§8-2-130(2)(b)** prohibits an employer from stating on an application for employment that a person with a criminal history may not apply, and from including on the application any question inquiring into an applicant's criminal history. Critically, the statute reaches the *application* stage — not merely the initial interview — and so it goes further than NYC Article 23-A or the [Los Angeles County Fair Chance Ordinance](/blog/los-angeles-county-fair-chance-ordinance-employers), both of which permit some pre-offer inquiry after the initial application. Colorado employers may inquire into criminal history *after* the initial application has been submitted, and may run a [county or national criminal background check](/blog/county-vs-national-criminal-background-check) at the post-application stage — but the application itself must be criminal-history-clean.

## The three narrow exemptions
Section §8-2-130(3) lists three exemptions, and they are the operative compliance map for any Colorado employer with a legitimate need to surface criminal history at the application stage. **Exemption 1** covers positions where federal, state, or local law expressly requires the criminal-history inquiry — the [FINRA Rule 3110](/blog/finra-rule-3110-background-check-employer-guide) registered-representative requirement and the [CMS exclusion-screening rules](/blog/cms-exclusion-screening-oig-leie-sam) map cleanly here. **Exemption 2** covers positions where federal, state, or local law expressly prohibits hiring an applicant with a particular criminal history — for example, certain childcare licensing rules under Colo. Rev. Stat. §26-6-104 that require fingerprint clearance and explicitly disqualify enumerated offenses. **Exemption 3** covers positions for which the employer is participating in a federal, state, or local government program designed to provide employment opportunities for persons with criminal histories — narrowly read by CDLE to mean second-chance hiring partnerships with specific written governmental authorization, not informal policy preferences. The CDLE has been explicit that an exemption claimed in a posting must specifically cite the statutory or regulatory authority requiring the inquiry; a generic "background check required" notice does not satisfy any of the three exemptions.

## How CCCA stacks against the federal FCRA and Colorado's 2023 SB23-058
The Chance to Compete Act is a *timing* statute — it controls *when* an employer may ask about criminal history — while the federal FCRA is a *procedure* statute that controls *how* an employer may use criminal-history data once it is properly obtained. Both apply concurrently in Colorado. An employer that holds the criminal-history inquiry until after the initial application complies with CCCA, but the [§604(b) disclosure-and-authorization stack](/blog/fcra-604b-disclosure-authorization), the [§615 pre-adverse-action letter clock](/blog/pre-adverse-five-business-day-clock), and the [§623 furnisher-dispute machinery](/blog/fcra-615-623-employer-duties) still attach to the actual criminal record pull. The 2023 Job Application Fairness Act (SB23-058, codified at Colo. Rev. Stat. §8-2-131) adds a parallel age-screening restriction that prohibits inquiring on the application about an applicant's age, date of birth, or date of attendance at or graduation from an educational institution — a rule worth surfacing here because the same Colorado application that has been scrubbed of criminal-history questions must also be scrubbed of these age proxies, and many national templates fail both screens together.

## What to fix this quarter
Audit Colorado hiring against three artifacts. First, the job-posting and application templates: every Colorado posting and online application form should be scanned for criminal-history language and age-proxy language, and the conjoined CCCA-plus-SB23-058 scrub should be the standard before the posting goes live. Second, the third-party-staffing handoff: CDLE treats the staffing agency and the employer as jointly responsible for the application form a candidate actually completes, so the same audit needs to run on every ATS template a staffing vendor surfaces under your brand. Third, the post-application criminal inquiry workflow: once the initial application clears CCCA, the post-application criminal screen should land inside a documented FCRA stack with adjudication aligned to the [EEOC Title VII disparate-impact framework](/blog/eeoc-title-vii-disparate-impact-screening). Employers running a Colorado-aware screening package or working through the multistate ban-the-box matrix with us at [contact](/contact) can pull the [compliance hub](/compliance) for the full CCCA-plus-FCRA-plus-SB23-058 layered model.`,
};
