import type { BlogPost } from "@/lib/blog";
export const post: BlogPost = {
  slug: "finra-rule-3110-background-check-employer-guide",
  title:
    "FINRA Rule 3110(e) Background Checks: Form U4 Fingerprinting and Investigation Duties",
  metaTitle: "FINRA Rule 3110(e) Background Check Guide 2026",
  metaDescription:
    "FINRA Rule 3110(e) makes broker-dealers verify every Form U4 within 30 days and fingerprint each registered person. Here is exactly how that intersects with FCRA hiring in 2026.",
  excerpt:
    "FINRA Rule 3110(e) requires broker-dealers to verify the accuracy of every Form U4 within 30 days and to fingerprint every registered person. Here is how that duty intersects with FCRA pre-employment screening in 2026.",
  publishedAt: "2026-05-18",
  readingMinutes: 6,
  author: "Rapid Hire Compliance Team",
  tags: ["finra", "compliance", "financial-services"],
  body: `Broker-dealers and their associated persons sit inside a regulatory regime no other industry deals with. Securities Exchange Act §17(f)(2) requires fingerprint submission to the Attorney General for every person engaged in the securities business. **FINRA Rule 3110(e)** — adopted in 2015 — operationalizes that statute by making each member firm responsible for verifying the accuracy and completeness of every **Form U4** within thirty calendar days of filing, and for written procedures that would reasonably uncover statutory disqualifications. Firms leaning on a generic FCRA pre-employment background check as their sole U4 verification expose themselves to enforcement, customer-arbitration, and registration-denial risk. This guide walks through the rule, where it overlaps with the FCRA, and how compliance and HR should split the work.
## What Rule 3110(e) actually requires
Rule 3110(e) imposes three operational duties on every FINRA member firm. **First**, the firm must establish and maintain written procedures reasonably designed to verify the accuracy and completeness of the information contained in an applicant's Form U4. **Second**, the verification must be completed no later than thirty calendar days after the U4 is filed with the Central Registration Depository — the so-called "30-day rule." **Third**, the procedures must include a national search of reasonably available public records, which FINRA's Notice 15-05 clarified means at minimum a federal criminal records search, a county criminal records search where the applicant has lived or worked in the past three years, a bankruptcy and civil-litigation public-records search, and an education and employment verification.
## How it overlaps with FCRA pre-employment screening
The U4 verification duty is **not** a substitute for the FCRA pre-employment process — and the FCRA is not a substitute for U4 verification. They run in parallel and they are scoped differently. The FCRA pre-employment background check is a permissible-purpose [consumer report](/blog/fcra-604b-disclosure-authorization) ordered for an employment decision and bounded by the **seven-year rule** under 15 U.S.C. §1681c. The U4 verification, by contrast, has no seven-year cap on disclosable matters: questions 14A, 14B, 14C, 14D, and 14E ask about regulatory and criminal history with **no time limit**, and the firm's verification must reach back as far as the questions reach.
This creates two practical adjudication problems. A criminal matter older than seven years that the FCRA report would not surface still has to be confirmed via the U4 questionnaire and disclosed to FINRA. A civil-litigation matter that does not appear on the FCRA report at all may still be a U4 question 14I disclosure if it involved an investment-related allegation. Compliance has to assume the FCRA report is the floor, not the ceiling, of the verification.
## Fingerprint submission under §17(f)(2)
Every registered person — every person who effects securities transactions or is engaged in the management of the broker-dealer — must be fingerprinted under §17(f)(2). Member firms collect fingerprints electronically through FINRA's Web CRD and submit them to the FBI, which returns a federal criminal-history record. This is **not** the same data set as a commercial FCRA federal-criminal search. The FBI Identification Record draws from CJIS records that include arrests without disposition, dismissed charges, and pre-conviction matters that the FCRA's exclusion rules at 15 U.S.C. §1681c forbid a CRA from reporting after seven years. Compliance therefore must adjudicate fingerprint hits separately from FCRA report hits, and must treat the FBI record as authoritative for U4 question 14B disclosures even when the FCRA report does not surface the same matter.
## The statutory-disqualification overlay
Section 3(a)(39) of the Exchange Act and FINRA By-Laws Article III, Section 4 list the events that statutorily disqualify a person from association with a member firm. The list includes felony convictions within the last ten years, securities-related misdemeanor convictions within the same window, willful violations of the federal securities laws, expulsion from a self-regulatory organization, and SEC injunctive orders. A pre-employment screen that surfaces any of these requires immediate compliance review and, where the firm wishes to associate with the person notwithstanding the disqualification, a Form MC-400 statutory-disqualification application to FINRA before registration.
## What compliance and HR should split
Three concrete duties have to land somewhere. **Compliance** owns U4 question accuracy, fingerprint submission and adjudication, statutory-disqualification analysis, and the 30-day verification window. **HR** owns the FCRA disclosure-and-authorization paperwork, the [adverse-action workflow](/blog/adverse-action-letter-fcra-template), and the state-law overlays that the FCRA report is bound by. Both functions need to share the same case file: a U4 disclosure that does not match the FCRA report needs reconciliation before registration, and an FCRA hit that the U4 did not disclose may itself be a 14M "false statement" disclosure trigger.
## What to fix today
Three steps. Audit the firm's written supervisory procedures to confirm the 30-day verification clock is built into the registration workflow, with documented sign-off. Confirm the [pre-employment screen package](/services) for registered associates includes federal criminal, multi-county criminal across the past three years' addresses, civil-litigation, and education and employment verification — the Notice 15-05 floor. Review fingerprint-adjudication procedures so that FBI-record matters older than seven years are still surfaced to compliance, even though the FCRA report excludes them. Our [healthcare credentialing parallel](/blog/healthcare-credentialing-vs-background-check) explains the same compliance-plus-FCRA two-track posture for clinical hires; financial-services teams can request a tailored package on the [pricing page](/pricing) or talk through the program design at [contact](/contact).`,
};
