import type { BlogPost } from "@/lib/blog";
export const post: BlogPost = {
  slug: "maryland-jafa-credit-history-employer-guide",
  title:
    "Maryland JAFA: The Credit-History Restriction Every Employer Hiring in MD Has To Operationalize",
  metaTitle: "Maryland JAFA Credit-History Employer Guide 2026",
  metaDescription:
    "Maryland's Job Applicant Fairness Act (Lab. & Empl. §3-711) bans most credit-history checks pre-offer. Here is the 2026 compliance map, exemptions, and penalty exposure.",
  excerpt:
    "Maryland's Job Applicant Fairness Act restricts credit-history use in hiring and discipline, with eight narrow exemptions and a private right of action through the Commissioner of Labor. We map the 2026 compliance scaffold for multistate employers.",
  publishedAt: "2026-05-28",
  readingMinutes: 6,
  author: "Rapid Hire Compliance Team",
  tags: ["maryland", "credit-checks", "fair-chance", "compliance", "fcra"],
  body: `**Maryland JAFA compliance** is the quietest credit-history audit we run, and it is also the one most often missed by national employers who assume the federal [FCRA disclosure framework](/blog/fcra-604b-disclosure-authorization) is sufficient cover. The **Job Applicant Fairness Act** — Md. Code, Lab. & Empl. **§3-711** — has been on the books since 2011 but was materially sharpened by 2023 Maryland Department of Labor enforcement guidance and by a Commissioner of Labor and Industry settlement order against a Baltimore staffing agency that highlighted just how narrow the statute's exemptions actually are. JAFA bars most Maryland employers from using a job applicant's or employee's **credit report or credit history** in hiring, firing, or compensation decisions, and the 2024 Maryland General Assembly's Cannabis Reform Act amendments added a parallel restriction on cannabis-related conviction records that interacts with the credit-history regime in ways multistate buyers regularly underestimate.

## What JAFA actually restricts
The statute's operative duty is in §3-711(b): a Maryland employer "may not use an applicant's or employee's credit report or credit history in determining whether to deny employment to the applicant, discharge the employee, or determine compensation or the terms, conditions, or privileges of employment." That language is broader than the federal FCRA in two important ways. First, it reaches *post-hire* discipline and pay decisions, not just pre-employment screening — a Maryland employer that demotes or denies a promotion based on a debt-collection entry violates the statute even if the underlying credit report was obtained lawfully years earlier. Second, the prohibition runs against the *use* of the report, not merely the *pulling* of it; an employer who orders a credit-history check but then bases the no-hire on the credit data still violates §3-711, regardless of any separate pretext. The Maryland Commissioner of Labor and Industry is empowered to investigate complaints, assess civil penalties up to $500 for a first violation and $2,500 for subsequent violations, and to pursue injunctive relief — and aggrieved applicants have a private right of action with attorney fees under §3-711(g).

## The eight exemptions and the credit-relevance test
JAFA lists eight narrow exemptions in §3-711(c)–(d), and they are the operative compliance map for any Maryland employer who genuinely needs credit data. **Exemption 1** covers positions at financial institutions chartered under federal or Maryland law — the [FINRA Rule 3110](/blog/finra-rule-3110-background-check-employer-guide) registered-representative carveout maps cleanly here. **Exemption 2** covers positions requiring a federal security clearance under Executive Order 12968. **Exemption 3** covers positions involving fiduciary responsibility to the employer with authority to issue payments, transfer money, or enter contracts on behalf of the employer in excess of $500. **Exemption 4** covers positions with access to confidential business or proprietary information — narrowly read by Maryland DOL to mean trade-secret-protected data, not generic business records. **Exemption 5** covers managerial positions involving direction or control of the business. **Exemption 6** covers positions with expense-account access. **Exemption 7** covers positions with access to personal information of others — also narrowly read to mean the kind of identity-document access that creates fraud risk, not casual contact with names and addresses. **Exemption 8** is the residual catch-all where state or federal law independently requires the credit check. Critically, the statute is explicit that the exemption must apply to the *specific position*, not to the employer generally; a Maryland fintech cannot pull credit history on a marketing coordinator just because the company is a financial institution.

## How JAFA stacks against FCRA and the Cannabis Reform Act amendments
Maryland JAFA is independent of, and additive to, the federal FCRA — a credit report pulled for a Maryland role still requires the [§604(b) disclosure-and-authorization stack](/blog/fcra-604b-disclosure-authorization), the [§615 pre-adverse-action letter clock](/blog/pre-adverse-five-business-day-clock), and the [§623 furnisher dispute machinery](/blog/fcra-615-623-employer-duties), even if one of the eight JAFA exemptions applies. Where JAFA changes the federal default is in the *content* of the adverse-action letter: a Maryland Commissioner of Labor settlement order in 2023 took the position that an adverse-action letter citing a credit-history reason without identifying which of the eight JAFA exemptions the employer relied on is itself evidence of a violation. The 2024 Cannabis Reform Act amendments at Md. Code, Health-General §13-3301 et seq. layer a separate restriction: a Maryland employer may not consider a cannabis-related conviction record older than three years for most non-safety-sensitive positions, and a credit-history check that surfaces collection entries tied to cannabis-related arrests must be scrubbed of those entries before any hiring decision is made. Employers running Maryland hires against a multistate [screening package](/pricing) should layer JAFA on top of the [ban-the-box framework](/blog/ban-the-box-fair-chance-hiring) rather than treating them as alternatives.

## What to fix this quarter
Audit Maryland hiring against three artifacts. First, the position-level credit-relevance matrix: every Maryland role should be tagged with its §3-711(c) exemption category — or, if none applies, flagged as a no-credit lane regardless of national policy. Second, the adverse-action letter template: every Maryland letter citing credit-history reasons should specify the exemption category and tie the credit fact to a documented job-relevance finding. Third, the Cannabis Reform Act scrub: collection entries surfaced through a credit pull that trace to cannabis-related arrests over three years old must be filtered before the hiring decision. Employers running a Maryland-aware screening stack or working through the multistate credit-history matrix with us at [contact](/contact) can pull the [compliance hub](/compliance) for the full JAFA-plus-FCRA-plus-Cannabis-Reform-Act layered model.`,
};
