import type { BlogPost } from "@/lib/blog";
export const post: BlogPost = {
  slug: "massachusetts-cori-employer-guide",
  title:
    "Massachusetts CORI: An Employer's Guide to iCORI, Lookback Caps, and the §171A Acknowledgment",
  metaTitle: "Massachusetts CORI Employer Guide 2026",
  metaDescription:
    "Massachusetts CORI gives employers conditional access to state criminal records under M.G.L. c.6 §172. Here is how iCORI registration, lookback caps, and §171A actually work.",
  excerpt:
    "Massachusetts CORI access is conditional, audited, and tightly capped by statute. This guide walks employers through iCORI registration, the seven- and ten-year lookback rules, the §171A acknowledgment, and the FCRA overlay that still applies.",
  publishedAt: "2026-05-21",
  readingMinutes: 6,
  author: "Rapid Hire Compliance Team",
  tags: ["compliance", "massachusetts", "criminal-records"],
  body: `Massachusetts runs one of the country's most distinctive criminal-history frameworks. **Criminal Offender Record Information**, or **CORI**, is the state-controlled record set that the Department of Criminal Justice Information Services (DCJIS) makes available to employers under **M.G.L. c.6 §§167–178B**. The 2010 CORI reform act and its 2012 implementing regulations at **803 CMR 2.00** redrew the rules: who can see what, how far back, with which forms on file, and under which audit obligations. An employer that orders a CORI without the iCORI registration, without the §171A acknowledgment in the file, or without the written CORI policy now required for any employer requesting more than fifteen records a year is exposed to a Massachusetts Attorney General enforcement action that is genuinely separate from FCRA exposure.
## What CORI actually contains, and what it does not
A CORI record is the state-controlled view of Massachusetts criminal court history. It includes adult open and closed criminal cases, juvenile delinquency adjudications in narrow categories, and pending charges. It does **not** include sealed records, expunged records, non-conviction data older than the statutory lookback window, dismissed cases that resolved without a finding of guilt where the seven-year window has run, or arrests without prosecution. It also does not include out-of-state criminal history — which is why a Massachusetts CORI is never a substitute for the [multi-jurisdictional criminal search](/blog/county-vs-national-criminal-background-check) most employers also need to run.
## The iCORI portal and Standard Access vs Required Access
Every employer that wants to view CORI must register on the **iCORI** portal operated by DCJIS. The portal sorts requesters into access levels. **Standard Access**, the default for general employers, returns convictions and pending cases inside the statutory lookback window. **Required Access**, available to employers that screen for positions involving children, the elderly, or disabled persons under specific statutes, returns a longer history and additional record types. Choosing the wrong access level is itself a compliance error: a long-term-care provider that runs Standard Access misses the very records the statute requires it to see, and a general employer that holds itself out as a Required Access requester to capture more history exceeds its statutory authority.
## The seven- and ten-year lookback caps under §172
Section 172 caps the reportable window on most CORI records. **Misdemeanor convictions** are reportable for **five years** from the date of disposition or release from incarceration, whichever is later. **Felony convictions** are reportable for **ten years** on the same trigger. Pending charges are always reportable regardless of age, and a small set of statutorily enumerated offenses — murder, manslaughter, and most serious sex offenses — are reportable indefinitely. These caps are tighter than the FCRA's general seven-year rule on adverse non-conviction information, so the FCRA is the floor and §172 is often the operative ceiling.
## The §171A acknowledgment: the form most employers forget
**M.G.L. c.6 §171A** requires that before an employer can request a CORI, the subject must sign an acknowledgment form authorizing the request. The form must contain specific language identifying the requester, the purpose of the request, and the subject's rights. The DCJIS publishes a model acknowledgment, and using a substantially equivalent form is permitted. Two practical traps: the acknowledgment is good for **one year** unless the subject re-acknowledges, and it is **separate** from the [FCRA §604(b) standalone disclosure and authorization](/blog/fcra-604b-disclosure-authorization) that the consumer reporting agency assembling the report also needs. A clean Massachusetts file has both forms, dated and signed, in the candidate's pre-hire packet.
## The written CORI policy + self-audit triggers
Any employer requesting **more than fifteen CORI records in a calendar year** must adopt a written CORI policy that meets the DCJIS model. The policy has to spell out the positions for which CORI will be requested, how the records will be used in adjudication, who within the organization can see them, and how the employer will conduct the annual self-audit DCJIS requires under 803 CMR 2.14. Employers also have to provide the subject with a copy of the CORI record before making an adverse decision and give the subject a reasonable opportunity to dispute the accuracy of the record — a process structurally similar to the federal pre-adverse-action sequence, but anchored in state statute.
## What to fix today
Three concrete steps. Confirm iCORI registration is current and the access level matches the population being hired; mismatched access is a compliance finding waiting to happen. Audit the candidate file for both the [§171A acknowledgment](/compliance) and the FCRA §604(b) standalone disclosure, signed within one year and stored in the offer packet. Confirm a written CORI policy is on file and an annual self-audit was run if the employer crossed the fifteen-records threshold last year. Operations teams running Massachusetts hiring at scale can request a [tailored screening package](/pricing) that bundles CORI, FCRA-compliant disclosure, and multi-state criminal in one workflow, or talk through the iCORI access-level analysis with us at [contact](/contact). The federal compliance overlay is the same structure detailed in our [FCRA compliance guide](/blog/fcra-compliance-guide); CORI is what sits on top of it in Massachusetts.`,
};
