import type { BlogPost } from "@/lib/blog";
export const post: BlogPost = {
  slug: "michigan-ichat-clean-slate-employer-guide",
  title:
    "Michigan ICHAT and the Clean Slate Act: The Background-Check Stack Every Employer Hiring in MI Has to Operationalize",
  metaTitle: "Michigan ICHAT + Clean Slate Act Employer Guide 2026",
  metaDescription:
    "Michigan ICHAT plus the 2023 Clean Slate Act (MCL §780.621g) automatically seals qualifying convictions. Here is the 2026 employer compliance map and adjudication scaffold.",
  excerpt:
    "Michigan's Internet Criminal History Access Tool (ICHAT) is the only authoritative state criminal-record source, and the 2023 Clean Slate Act overlays automatic sealing on top. We map the 2026 employer compliance scaffold.",
  publishedAt: "2026-05-31",
  readingMinutes: 6,
  author: "Rapid Hire Compliance Team",
  tags: ["michigan", "clean-slate", "criminal-records", "compliance", "fair-chance"],
  body: `**Michigan ICHAT and Clean Slate Act compliance** is the multistate audit our Detroit, Grand Rapids, and Ann Arbor clients most often misread, because the Michigan framework asks employers to coordinate three things at once that most legacy CRAs surface as separate workflows. The Michigan State Police operates the **Internet Criminal History Access Tool (ICHAT)** under the authority of MCL §28.214 — the only authoritative state-level criminal-record source for the Commonwealth — and the 2023 **Clean Slate Act**, codified at MCL §§780.621–780.621g and brought to full operational effect in April 2023, overlays an *automatic* sealing rule on top of ICHAT for qualifying misdemeanor and felony convictions. The result is a hiring-funnel architecture where the state record source, the sealing framework, and the [federal FCRA disclosure stack](/blog/fcra-604b-disclosure-authorization) all have to move in lockstep — and they usually do not in employer environments built around generic national-database screening.

## What ICHAT is and what it is not
ICHAT is a name-based search against the Michigan State Police Criminal History Record (CHR) database — the same database fed by every Michigan booking and court disposition since the early 1970s. It is *not* a fingerprint-based search, which means it is subject to a higher false-positive rate than a Michigan fingerprint clearance (the latter required for certain licensed positions under MCL §28.243). And it is *not* a national database — it returns only Michigan dispositions. Employers running a Michigan candidate through a multistate screening package without an ICHAT pull are working from secondary aggregator data, and the resulting [county-versus-national criminal-search gap](/blog/county-vs-national-criminal-background-check) is the single most common Michigan adjudication error we see when we onboard a new client off a legacy vendor. The Michigan State Police charges $10 per ICHAT search and returns results in seconds via the state portal, so cost is not a defensible reason to skip the pull.

## What the Clean Slate Act actually seals
The 2023 Clean Slate Act, building on Public Act 187 of 2020 and finalized at MCL §780.621g, creates *automatic* sealing for up to four misdemeanors and up to two felonies on a defined clean-record clock — seven years from sentence completion for misdemeanors and ten years from sentence completion for felonies — with categorical exclusions for assaultive offenses (MCL §770.9a(1)(a)), serious misdemeanors as defined in MCL §780.811, and any offense punishable by ten or more years' imprisonment. Crucially, MCL §780.621g uses a *dissemination restriction* model — the sealed records remain in the CHR but are not returned through ICHAT to private employers — which means a properly executed Michigan screen automatically excludes Clean Slate-sealed records from the employer-facing report. The compliance failure mode is the secondary-aggregator pull: a multistate national-database vendor whose underlying data was harvested before April 2023 can still surface a sealed record, and using that record creates direct §780.623 exposure on top of the parallel [FCRA §615 pre-adverse-action duties](/blog/pre-adverse-five-business-day-clock).

## How ICHAT and Clean Slate stack against §780.623 and the federal FCRA
Section 780.623 makes it a misdemeanor and a civil-rights violation for an employer to use a record sealed under §780.621g in a hiring decision, and it pairs the criminal exposure with a private right of action allowing the applicant to recover actual damages, costs, and attorney's fees. The federal FCRA layer attaches separately: when the screen is run through a CRA, the [§604(b) disclosure-and-authorization stack](/blog/fcra-604b-disclosure-authorization), the [§615 adverse-action sequence](/blog/fcra-615-623-employer-duties), and the [§613 reporting-currency duties](/blog/fcra-613-public-record-reporting) all attach regardless of the §780.623 question. The two regimes interlock cleanly: §780.623 controls *what records may be used*, the FCRA controls *how the record-pull and adverse-action sequence have to be procedurally executed*, and a Michigan employer needs both layers documented in the adjudication SOP to be defensible.

## What to fix this quarter
Audit Michigan hiring against three artifacts. First, the screening package itself: any Michigan candidate should be running through an ICHAT pull (not an aggregator substitute) so the Clean Slate dissemination restriction is actually honored at the data layer. Second, the adjudication matrix: returned records should be cross-checked against the §780.621g sealing-eligibility clocks so that even an ICHAT pull from a non-Michigan CRA does not surface a record that should have been sealed before reporting. Third, the [adverse-action sequence](/blog/pre-adverse-five-business-day-clock): every Michigan adverse action should run inside a five-business-day pre-adverse window with the [EEOC Title VII disparate-impact framework](/blog/eeoc-title-vii-disparate-impact-screening) layered on top. Multistate employers building a Michigan-aware screening stack can pull our [compliance hub](/compliance) for the full ICHAT-plus-Clean-Slate-plus-FCRA layered model or open a scoping conversation through [contact](/contact).`,
};
