import type { BlogPost } from "@/lib/blog";
export const post: BlogPost = {
  slug: "ofac-sanctions-screening-employment",
  title:
    "OFAC Sanctions Screening for Employment: The SDN List, the 50% Rule, and Strict Liability",
  metaTitle: "OFAC Sanctions Screening for Hiring 2026",
  metaDescription:
    "OFAC sanctions screening at the hire is a strict-liability obligation distinct from I-9, E-Verify, and CMS exclusions. Here is how SDN, the 50% Rule, and §501.601 actually apply.",
  excerpt:
    "OFAC screening at the hire is a federal strict-liability obligation that sits next to — not inside — I-9 and CMS exclusion workflows. This is how the SDN list, the 50% Rule, and the §501.601 record-keeping duty actually apply to employment.",
  publishedAt: "2026-05-23",
  readingMinutes: 6,
  author: "Rapid Hire Compliance Team",
  tags: ["compliance", "sanctions", "ofac"],
  body: `Most U.S. employers treat **OFAC sanctions screening** as a vendor-side concern: something procurement does before issuing a purchase order, not something HR does before issuing an offer letter. That mental model breaks the law. The **Office of Foreign Assets Control** administers economic sanctions under the **International Emergency Economic Powers Act** and **31 C.F.R. Parts 501–598**, and the underlying prohibition is broad: U.S. persons — which includes any U.S. employer and any U.S. entity — may not engage in "transactions" with blocked persons, and the definition of "transaction" reaches well past commercial purchases. Paying wages to a person on the **Specially Designated Nationals (SDN) list** is a sanctions violation. So is paying wages to an entity that is 50% or more owned by SDNs under OFAC's **50% Rule**. So is paying wages to a person blocked under one of the more recent program-specific designations like **Executive Order 13694** (malicious cyber-enabled activities) or **Executive Order 13848** (election-interference). OFAC's enforcement framework is **strict liability**: the employer's good-faith ignorance of the SDN designation is not a defense, only a possible mitigating factor in the penalty calculation.
## What the SDN list actually contains
The SDN list is OFAC's consolidated list of individuals and entities whose assets must be blocked and with whom U.S. persons may not transact. It includes program-specific designations under each sanctions regime — Cuba, Iran, North Korea, Russia, Venezuela, terrorism, narcotics, cyber, election interference, transnational criminal organizations, foreign corruption, human rights, and a growing list of country-specific or activity-specific programs. The list is updated continuously; OFAC publishes machine-readable updates daily. An employer's screening obligation is not "we ran the SDN list on hire date and put a copy in the file" — it is to avoid the prohibited transaction for as long as the employment relationship continues, which means the screen has to be **re-run** on a defined cadence and at any event (name change, new identifiers, change of role) that could meaningfully alter the screening hit.
## OFAC is structurally distinct from I-9, E-Verify, and CMS exclusions
The most common HR error is conflating OFAC with adjacent workflows. **I-9 and E-Verify** — covered in our [I-9 and E-Verify employer guide](/blog/i9-e-verify-employer-guide) — answer "is this person authorized to work in the United States?" That is an immigration question. OFAC answers "is this person on a list with whom my organization is federally prohibited from transacting?" That is a sanctions question. A person can be fully work-authorized and still SDN-listed; a person can be SDN-listed under a non-immigration program and still pass E-Verify. Likewise, the **CMS exclusion lists** — OIG-LEIE, SAM, and state Medicaid exclusion lists detailed in our [CMS exclusion screening guide](/blog/cms-exclusion-screening-oig-leie-sam) — answer "is this person barred from federal-payor reimbursement?" That is a payor question. OFAC is none of those.
## The 50% Rule that quietly catches entity transactions
OFAC's **50% Rule** (OFAC FAQ #401 and the August 2014 guidance) says that any entity owned 50% or more — directly or indirectly, individually or in the aggregate — by one or more SDN-listed persons is **itself** treated as SDN-listed, even if it does not appear on the list by name. For employment, the rule matters most for the staffing-agency and contractor population: a payroll relationship that runs through an intermediary entity is blocked if SDN ownership exceeds the threshold. The relationship between staffing-vendor risk and OFAC is one of the reasons we recommend pairing OFAC screening with [continuous employee monitoring](/blog/continuous-employee-monitoring) on contingent-workforce populations.
## §501.601 record-keeping turns the screen into evidence
**31 C.F.R. §501.601** requires every U.S. person to keep a full and accurate record of every transaction subject to OFAC regulations for **five years**. For an employer this means more than a screenshot of the SDN search; it means the timestamped search record, the parameters used (name spellings, DOB, country of birth, identifiers), the result returned, and the reviewer's resolution of any "potential match" — including a false-positive memo where applicable. The record-keeping obligation is itself an OFAC violation when neglected, and it is the first request in an OFAC subpoena.
## What to fix today
Three concrete steps. Confirm SDN and applicable program-specific lists are part of the pre-hire screen on every population, not just contingent or foreign-national hires. Confirm the screen is re-run on a defined cadence — continuous monitoring is the operational baseline — and that the 50% Rule analysis is documented for entity-mediated payroll relationships. Confirm §501.601 records are stored for five years and retrievable on subpoena. Operations teams designing or auditing an OFAC program can request a [tailored screening package](/pricing) or talk through the SDN + 50% Rule workflow with us at [contact](/contact); the federal compliance backbone runs alongside the standard [FCRA guide](/blog/fcra-compliance-guide).`,
};
