import type { BlogPost } from "@/lib/blog";
export const post: BlogPost = {
  slug: "pennsylvania-chria-9125-employer-background-check-guide",
  title:
    "Pennsylvania CHRIA §9125: The Job-Relevance Test Every Employer Hiring in PA Has To Pass",
  metaTitle: "Pennsylvania CHRIA §9125 Employer Guide 2026",
  metaDescription:
    "18 Pa. C.S. §9125 limits Pennsylvania employers to felony and misdemeanor convictions that relate to the job. Here is the 2026 compliance map and litigation exposure.",
  excerpt:
    "Pennsylvania's Criminal History Record Information Act §9125 is the most restrictive job-relevance test in the Northeast. We map the felony-and-misdemeanor-only rule, the written-notice duty, the Philadelphia overlay, and the live class-action exposure heading into 2026.",
  publishedAt: "2026-05-26",
  readingMinutes: 6,
  author: "Rapid Hire Compliance Team",
  tags: ["pennsylvania", "chria", "criminal-records", "fair-chance", "compliance"],
  body: `**Pennsylvania CHRIA §9125 compliance** is the most under-built control in the screening stacks we audit for employers hiring across Philadelphia, Pittsburgh, and Allentown. **18 Pa. C.S. §9125** — Pennsylvania's Criminal History Record Information Act — is not a ban-the-box ordinance and is not a §1681 federal disclosure. It is a substantive state-law limit on what conviction information an employer may consider, and it operates regardless of whether a [consumer reporting agency](/blog/icraa-investigative-consumer-report-definition) was involved or whether the candidate self-disclosed. The statute restricts use of criminal-history information to **felony and misdemeanor convictions** that relate to the applicant's suitability for the position, requires written notice to the applicant when conviction information is the basis of an adverse decision, and is enforced through private suits with statutory damages and attorney fees. Class actions filed in 2024 and 2025 against multistate retailers and staffing platforms have made it the highest-leverage state screening statute in the Mid-Atlantic.

## What §9125 actually says, in operative terms
The statute has three operative subsections. **§9125(a)** restricts what a Pennsylvania employer may consider: only felony and misdemeanor convictions. Arrests not leading to conviction, summary offenses, expunged or pardoned records, and ARD dispositions are off-limits as a basis for an adverse hiring decision. **§9125(b)** is the job-relevance test: an employer may consider only those felony and misdemeanor convictions that "relate to the applicant's suitability for employment in the position for which he has applied." This is a substantive limit, not a procedural one — there is no safe harbor for considering an unrelated conviction even with consent. **§9125(c)** is the notification duty: when an employer's decision not to hire is based in whole or in part on criminal-history information, the employer must notify the applicant in writing. The notice obligation runs in parallel to FCRA §615(a) [pre-adverse and adverse-action notices](/blog/pre-adverse-five-business-day-clock) but is independent — a §615(a) packet alone does not satisfy §9125(c).

## The job-relevance test in litigation
Pennsylvania courts have read the §9125(b) job-relevance test as a fact-intensive inquiry, not a rubber stamp. The leading authority — *Negron v. Sch. Dist. of Philadelphia*, 994 F. Supp. 2d 663 (E.D. Pa. 2014) — held that an employer asserting a §9125(b) defense must articulate a specific connection between the conviction and the duties of the position, and conclusory references to "honesty" or "trust" are insufficient. The Third Circuit's reasoning in *El v. SEPTA*, 479 F.3d 232, although decided under Title VII, has been imported into §9125 analysis by Pennsylvania trial courts as persuasive authority on what counts as a job-related conviction. The practical takeaway: a Pennsylvania employer running a [county vs. national criminal background check](/blog/county-vs-national-criminal-background-check) cannot disqualify on a 2014 retail theft for an electrician position without documenting why that record disqualifies the candidate from this specific role.

## Philadelphia and Pittsburgh overlays make the floor higher
Pennsylvania has no statewide ban-the-box law, but **Philadelphia's Fair Criminal Records Screening Standards Ordinance** (Phila. Code §9-3404) layers on top of CHRIA for any employer with one or more employees in the city. The Philadelphia ordinance prohibits criminal-history inquiry until after a conditional offer, requires a multi-factor individualized assessment when an employer wants to rescind, and entitles the applicant to a written explanation and a chance to respond. **Pittsburgh's Ban-the-Box ordinance** applies to city government and city contractors and adds the same individualized-assessment posture for those employers. Outside those cities, §9125 alone governs — but the §9125(b) job-relevance test is enforceable everywhere in the Commonwealth.

## What to fix this quarter
Map every Pennsylvania hiring lane against §9125 in three steps. First, audit the disqualifying-criteria matrix: every felony or misdemeanor that triggers an adverse decision must have a written justification connecting it to the job duties of the role, and arrests, summary offenses, and ARD outcomes must be filtered out before a recruiter sees the report. Second, audit the adverse-action templates: §9125(c) written notice must reach the applicant, and it must be distinct from — or layered into — the FCRA pre-adverse and final adverse notices. Third, separate the Philadelphia lane: applicants for any role in the city should hit a conditional-offer gate before any criminal-history inquiry, and the rescission workflow should produce the multi-factor individualized assessment under §9-3404. Employers running multistate hiring should pull a [Pennsylvania-aware screening package](/pricing) or work the §9125 + Philadelphia overlay with us at [contact](/contact); the [compliance hub](/compliance) maps how CHRIA stacks with FCRA §615, EEOC guidance, and the Mid-Atlantic clean-slate trend in one matrix.`,
};
