import type { BlogPost } from "@/lib/blog";
export const post: BlogPost = {
  slug: "virginia-fair-chance-hiring-employer-guide",
  title:
    "Virginia Fair Chance Hiring: The Marijuana-Sealing and Ban-the-Box Stack Multistate Employers Keep Misreading",
  metaTitle: "Virginia Fair Chance Hiring Employer Guide 2026",
  metaDescription:
    "Virginia automatically seals marijuana-misdemeanor convictions under Va. Code §19.2-389.3 and bans the box for state-agency hiring. Here is the 2026 employer compliance map.",
  excerpt:
    "Virginia's automatic marijuana-misdemeanor sealing under Va. Code §19.2-389.3 and the §40.1-28.7:8 ban-the-box rule for state hiring create a layered compliance stack that out-of-state employers routinely miss. We map the 2026 operational scaffold.",
  publishedAt: "2026-05-30",
  readingMinutes: 6,
  author: "Rapid Hire Compliance Team",
  tags: ["virginia", "ban-the-box", "fair-chance", "compliance", "criminal-records"],
  body: `**Virginia fair-chance hiring compliance** is the multistate audit our Northern Virginia and Hampton Roads clients most often misread, because the Commonwealth's framework is split across three statutes that came online in three different years and operate at three different layers of the hiring funnel. The 2021 marijuana-decriminalization package created an *automatic* sealing rule for marijuana-misdemeanor convictions at Va. Code **§19.2-389.3**. The 2020 ban-the-box statute at Va. Code **§40.1-28.7:8** restricts criminal-history inquiries by state agencies and contains a separate rule that any *private* employer learns about through the [federal FCRA disclosure stack](/blog/fcra-604b-disclosure-authorization). And the 2025 conforming amendments to **§19.2-392.7** through **§19.2-392.13** completed the broader expungement-and-sealing infrastructure that took effect July 1, 2025. Together they form the Virginia compliance scaffold a hiring team needs to operationalize before the first criminal-history report lands on an applicant.

## What Va. Code §19.2-389.3 actually does
Section §19.2-389.3 makes records of arrest, charge, or conviction for misdemeanor marijuana possession (former Va. Code §18.2-250.1) **automatically** unavailable in employer-facing background checks. The statute is structured as a *dissemination restriction*: the State Police and clerks of court are barred from disclosing those records to anyone other than law enforcement and certain enumerated agencies. That means a Virginia [county or national criminal background check](/blog/county-vs-national-criminal-background-check) properly run through a Virginia-licensed CRA will return *no hit* for a sealed marijuana misdemeanor, and the §19.2-389.3(D) rule expressly prohibits an employer from requiring an applicant to disclose information about the sealed offense. An applicant lawfully answers "no" to a criminal-history question covering only the sealed conviction, and adverse action grounded in that conviction creates direct §19.2-389.3 exposure on top of the parallel [FCRA §615 pre-adverse-action duties](/blog/pre-adverse-five-business-day-clock).

## The §40.1-28.7:8 state-agency ban-the-box rule
Section §40.1-28.7:8 — sometimes referenced as the Virginia Public Employment Reform Act — prohibits state agencies from including a question on the initial application about an applicant's criminal-history record. The statute reaches the *application* stage, parallel in structure to the [Colorado Chance to Compete Act §8-2-130 framework](/blog/colorado-chance-to-compete-act-employer-guide), and it permits the inquiry only after the agency has determined the applicant otherwise meets the position's minimum qualifications. The rule is narrower than the Colorado statute — it binds only state agencies, not private employers — but it carries a parallel rule at §40.1-28.7:8(B) that no state agency may require an applicant to disclose information sealed under §19.2-389.3 or the broader §19.2-392.7 expungement framework. Private Virginia employers contracting with the Commonwealth often see §40.1-28.7:8 surface in their procurement requirements and in flow-down clauses on state contracts, so the audit triggers there even if the statute does not directly bind the contractor.

## The 2025 §19.2-392.7 expungement-and-sealing infrastructure
The §19.2-392.7 through §19.2-392.13 framework that took full effect on July 1, 2025, dramatically expanded the universe of sealed records beyond marijuana misdemeanors. The framework creates *automatic* sealing for certain misdemeanor convictions after a seven-year clean record and *petition-based* sealing for many felony convictions after a ten-year clean record, all with the same §19.2-389.3-style dissemination restriction layered on top. The operational implication for an out-of-state employer is straightforward: a Virginia criminal-history report from a non-Virginia source that surfaces records pulled under the pre-2025 framework can return convictions that have since been sealed under §19.2-392.7 and that the employer is *prohibited* from using under §19.2-392.12. The freshness rule pairs cleanly with the [FCRA §613 reporting-currency duties](/blog/fcra-613-public-record-reporting) that hold the CRA accountable for re-pulling court records before reporting to an employer.

## What to fix this quarter
Virginia hiring should be audited against three artifacts. First, the application form: every Virginia application should be scrubbed of any question that asks about a sealed marijuana misdemeanor or that demands disclosure of expunged or sealed records, whether the candidate is applying for a state-agency or private-sector role. Second, the CRA contract: every Virginia screening package should explicitly require post-2025 court re-pulls so a sealed conviction cannot return as a stale "hit," and the [adjudication matrix](/blog/eeoc-title-vii-disparate-impact-screening) should treat sealed-record returns as automatic disqualifiers from the adverse-action stack rather than as fact patterns the recruiter has to interpret. Third, the state-contract procurement layer: any Virginia state contract should be reviewed for §40.1-28.7:8 flow-down language so the contractor's hiring funnel mirrors the agency's ban-the-box duty. Multistate employers building a Virginia-aware screening stack can pull our [Virginia compliance scaffold](/compliance) or open a scoping conversation through [contact](/contact).`,
};
